server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/test
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  cache:
    type: redis
  data:
    redis:
      host: localhost
      port: 6379

jwt-variables:
  KEY: authorization
  ISSUER: walkers
  EXPIRES_ACCESS_TOKEN_MINUTE: 60
  EXPIRES_REFRESH_TOKEN_MINUTE: 10080





